// generated by gentests.py, do not edit
// MonTanaMiniComputerTest.java

#ifdef NDEBUG
#undef NDEBUG
#endif
#include <assert.h>

#define PAIV_MTMC_IMPLEMENTATION
#include "paiv_mtmc16.h"
#include "platform.c"

int MtmcExecutableLoad(FILE* file, struct MtmcExecutable* exe) {
    FatalError();
    return 1;
}

static struct Platform _platform = {};

static void _MtmcTestInit(struct MtmcEmu* emu) {
    PlatformInit(&_platform);
    emu->platform = &_platform;
    MtmcInitMemory(emu);
}

//public class MonTanaMiniComputerTest {

    static void testSysCall(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        assert(MtmcGetStatus(&emu) == MtmcEmuStatus_READY);
        short haltInst = 0b0000000000000000; // sys halt
        MtmcExecInstruction(&emu, haltInst);
        assert(MtmcGetStatus(&emu) == MtmcEmuStatus_FINISHED);
    }

    static void testMov(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, T1, 0);

        short moveInst = 0b0000000100010000; // mov t1 t0
        MtmcExecInstruction(&emu, moveInst);

        assert(10 == MtmcGetRegisterValue(&emu, T0));
        assert(10 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testInc(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0);
        short incInst = 0b0000001000000001; // inc t0
        MtmcExecInstruction(&emu, incInst);
        assert(1 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testInc3(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0);
        short incInst = 0b0000001000000011; // inc t0
        MtmcExecInstruction(&emu, incInst);
        assert(3 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testDec(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0);
        short decInst = 0b0000001100000001; // Dec t0
        MtmcExecInstruction(&emu, decInst);
        assert(-1 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testDec3(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0);
        short decInst = 0b0000001100000011; // Dec t0
        MtmcExecInstruction(&emu, decInst);
        assert(-3 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testSeti(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0);
        short inst = 0b0000010000000011; // seti t0 3
        MtmcExecInstruction(&emu, inst);
        assert(3 == MtmcGetRegisterValue(&emu, T0));
    }

    /*
    static void testNoOp(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);

        short[] originalRegisters = Arrays.copyOf(MtmcRegisterFile, MtmcRegisterFile.length);
        byte[] originalMemory = Arrays.copyOf(MtmcMemory, MtmcMemory.length);

        short noop = 0b0000111111111111; // no-op
        MtmcExecInstruction(&emu, noop);

        boolean registersEqual = Arrays.equals(originalRegisters, MtmcRegisterFile);
        assert(registersEqual != 0);
        boolean memoryEqual = Arrays.equals(originalMemory, MtmcMemory);
        assert(memoryEqual != 0);
    }
    */

    static void testAdd(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 5);
        MtmcSetRegisterValue(&emu, T1, 10);

        short addInst = 0b0001000000000001; // add t0, t1
        MtmcExecInstruction(&emu, addInst);

        assert(15 == MtmcGetRegisterValue(&emu, T0));
        assert(10 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testSub(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, T1, 5);

        short subInst = 0b0001000100000001; // sub t0, t1
        MtmcExecInstruction(&emu, subInst);

        assert(5 == MtmcGetRegisterValue(&emu, T0));
        assert(5 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testMul(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, T1, 5);

        short mulInst = 0b0001001000000001; // mul t0, t1
        MtmcExecInstruction(&emu, mulInst);

        assert(50 == MtmcGetRegisterValue(&emu, T0));
        assert(5 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testDiv(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, T1, 5);

        short divInst = 0b0001001100000001; // div t0, t1
        MtmcExecInstruction(&emu, divInst);

        assert(2 == MtmcGetRegisterValue(&emu, T0));
        assert(5 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testMod(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, T1, 5);

        short modInst = 0b0001010000000001; // mod t0, t1
        MtmcExecInstruction(&emu, modInst);

        assert(0 == MtmcGetRegisterValue(&emu, T0));
        assert(5 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testAnd(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0b110);
        MtmcSetRegisterValue(&emu, T1, 0b011);

        short andInst = 0b0001010100000001; // and t0, t1
        MtmcExecInstruction(&emu, andInst);

        assert(0b010 == MtmcGetRegisterValue(&emu, T0));
        assert(0b011 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testOr(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0b100);
        MtmcSetRegisterValue(&emu, T1, 0b001);

        short orInst = 0b0001011000000001; // or t0, t1
        MtmcExecInstruction(&emu, orInst);

        assert(0b101 == MtmcGetRegisterValue(&emu, T0));
        assert(0b001 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testXor(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0b101);
        MtmcSetRegisterValue(&emu, T1, 0b011);

        short xorInst = 0b0001011100000001; // xor t0, t1
        MtmcExecInstruction(&emu, xorInst);

        assert(0b110 == MtmcGetRegisterValue(&emu, T0));
        assert(0b011 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testShiftLeft(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0b0101);
        MtmcSetRegisterValue(&emu, T1, 1);

        short shiftLeftInst = 0b0001100000000001; // shl t0, t1
        MtmcExecInstruction(&emu, shiftLeftInst);

        assert(0b01010 == MtmcGetRegisterValue(&emu, T0));
        assert(1 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testShiftRight(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0b0101);
        MtmcSetRegisterValue(&emu, T1, 1);

        short shiftLeftInst = 0b0001100100000001; // shr t0, t1
        MtmcExecInstruction(&emu, shiftLeftInst);

        assert(0b0010 == MtmcGetRegisterValue(&emu, T0));
        assert(1 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testMin(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 20);
        MtmcSetRegisterValue(&emu, T1, 10);

        short minInst = 0b0001101000000001; // min t0, t1
        MtmcExecInstruction(&emu, minInst);

        assert(10 == MtmcGetRegisterValue(&emu, T0));
        assert(10 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testMin2(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, T1, 20);

        short minInst = 0b0001101000000001; // min t0, t1
        MtmcExecInstruction(&emu, minInst);

        assert(10 == MtmcGetRegisterValue(&emu, T0));
        assert(20 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testMax(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 20);
        MtmcSetRegisterValue(&emu, T1, 10);

        short maxInst = 0b0001101100000001; // max t0, t1
        MtmcExecInstruction(&emu, maxInst);

        assert(20 == MtmcGetRegisterValue(&emu, T0));
        assert(10 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testMax2(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, T1, 20);

        short maxInst = 0b0001101100000001; // max t0, t1
        MtmcExecInstruction(&emu, maxInst);

        assert(20 == MtmcGetRegisterValue(&emu, T0));
        assert(20 == MtmcGetRegisterValue(&emu, T1));
    }

    static void testBitwiseNot(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0b010101);

        short bitwiseNotInst = 0b0001110000000000; // bnot t0
        MtmcExecInstruction(&emu, bitwiseNotInst);

        assert(~0b010101 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testNotWithZero(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0);

        short notInst = 0b0001110100000000; // not t0
        MtmcExecInstruction(&emu, notInst);

        assert(1 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testNotWithNonZeros(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1);

        short notInst = 0b0001110100000000; // not t0
        MtmcExecInstruction(&emu, notInst);
        assert(0 == MtmcGetRegisterValue(&emu, T0));

        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcExecInstruction(&emu, notInst);
        assert(0 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testNegate(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);

        short negInst = 0b0001111000000000; // neg t0
        MtmcExecInstruction(&emu, negInst);

        assert(-10 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testImmediateInstruction(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, DR, 10);

        short negInst = 0b0001111100000000; // imm add t0 10
        MtmcExecInstruction(&emu, negInst);

        assert(20 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testPush(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 5);

        short pushInst = 0b0010000000001101; // push t0, sp
        MtmcExecInstruction(&emu, pushInst);

        int newStackAddress = Mtmc_MEMORY_SIZE - 2;
        assert(newStackAddress == MtmcGetRegisterValue(&emu, SP));
        assert(5 == MtmcFetchWordFromMemory(&emu, newStackAddress));
    }

    static void testPop(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 0);
        MtmcSetRegisterValue(&emu, SP, 100);
        MtmcWriteWordToMemory(&emu, 100, (short) 10);

        short popInst = 0b0010000100001101; // pop t0, sp
        MtmcExecInstruction(&emu, popInst);

        assert(10 == MtmcGetRegisterValue(&emu, T0));
        assert(102 == MtmcGetRegisterValue(&emu, SP));
    }

    static void testDuplicate(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 100);
        MtmcWriteWordToMemory(&emu, 100, (short) 10);

        short duplicateInst = 0b0010001000001101; // dup sp
        MtmcExecInstruction(&emu, duplicateInst);

        assert(98 == MtmcGetRegisterValue(&emu, SP));
        assert(10 == MtmcFetchWordFromMemory(&emu, 98));
    }

    static void testSwap(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 10);
        MtmcWriteWordToMemory(&emu, 98, (short) 20);

        short swapIns = 0b0010001100001101; // swap sp
        MtmcExecInstruction(&emu, swapIns);

        assert(98 == MtmcGetRegisterValue(&emu, SP));
        assert(10 == MtmcFetchWordFromMemory(&emu, 98));
        assert(20 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testDrop(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 10);
        MtmcWriteWordToMemory(&emu, 98, (short) 20);

        short dropInst = 0b0010010000001101; // swap sp
        MtmcExecInstruction(&emu, dropInst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
    }

    static void testOver(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 10);
        MtmcWriteWordToMemory(&emu, 98, (short) 20);

        short overInst = 0b0010010100001101; // over sp
        MtmcExecInstruction(&emu, overInst);

        assert(96 == MtmcGetRegisterValue(&emu, SP));
        assert(10 == MtmcFetchWordFromMemory(&emu, 100));
        assert(20 == MtmcFetchWordFromMemory(&emu, 98));
        assert(10 == MtmcFetchWordFromMemory(&emu, 96));
    }

    static void testRot(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 96);
        MtmcWriteWordToMemory(&emu, 100, (short) 10);
        MtmcWriteWordToMemory(&emu, 98, (short) 20);
        MtmcWriteWordToMemory(&emu, 96, (short) 30);

        short rotInst = 0b0010011000001101; // over sp
        MtmcExecInstruction(&emu, rotInst);

        assert(96 == MtmcGetRegisterValue(&emu, SP));
        assert(20 == MtmcFetchWordFromMemory(&emu, 100));
        assert(30 == MtmcFetchWordFromMemory(&emu, 98));
        assert(10 == MtmcFetchWordFromMemory(&emu, 96));
    }

    static void testSopAdd(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 10);
        MtmcWriteWordToMemory(&emu, 98, (short) 20);

        short sopAddInst = 0b0010011100001101; // sop add sp
        MtmcExecInstruction(&emu, sopAddInst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(30 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testSopSub(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 20);
        MtmcWriteWordToMemory(&emu, 98, (short) 10);

        short sopSubInst = 0b0010011100011101; // sop sub sp
        MtmcExecInstruction(&emu, sopSubInst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(10 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testSopMul(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 20);
        MtmcWriteWordToMemory(&emu, 98, (short) 10);

        short sopMulInst = 0b0010011100101101; // sop mul sp
        MtmcExecInstruction(&emu, sopMulInst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(200 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testSopDiv(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 20);
        MtmcWriteWordToMemory(&emu, 98, (short) 10);

        short sopDivInst = 0b0010011100111101; // sop div sp
        MtmcExecInstruction(&emu, sopDivInst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(2 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testSopMod(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 20);
        MtmcWriteWordToMemory(&emu, 98, (short) 10);

        short sopModInst = 0b0010011101001101; // sop mod sp
        MtmcExecInstruction(&emu, sopModInst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(0 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testSopAnd(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 0b110);
        MtmcWriteWordToMemory(&emu, 98, (short) 0b011);

        short sopAndInst = 0b0010011101011101; // sop and sp
        MtmcExecInstruction(&emu, sopAndInst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(0b010 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testSopOr(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 0b100);
        MtmcWriteWordToMemory(&emu, 98, (short) 0b001);

        short sopOrInst = 0b0010011101101101; // sop or sp
        MtmcExecInstruction(&emu, sopOrInst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(0b101 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testSopXor(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 0b110);
        MtmcWriteWordToMemory(&emu, 98, (short) 0b011);

        short sopXorInst = 0b0010011101111101; // sop xor sp
        MtmcExecInstruction(&emu, sopXorInst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(0b101 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testSopShl(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 0b110);
        MtmcWriteWordToMemory(&emu, 98, (short) 1);

        short sopShlInst = 0b0010011110001101; // sop shl sp
        MtmcExecInstruction(&emu, sopShlInst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(0b1100 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testSopShr(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 0b110);
        MtmcWriteWordToMemory(&emu, 98, (short) 1);

        short sopShrInst = 0b0010011110011101; // sop shr sp
        MtmcExecInstruction(&emu, sopShrInst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(0b011 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testSopMin(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 10);
        MtmcWriteWordToMemory(&emu, 98, (short) 20);

        short inst = 0b0010011110101101; // sop min sp
        MtmcExecInstruction(&emu, inst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(10 == MtmcFetchWordFromMemory(&emu, MtmcGetRegisterValue(&emu, SP)));
    }

    static void testSopMin2(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 98, (short) 20);
        MtmcWriteWordToMemory(&emu, 100, (short) 10);

        short inst = 0b0010011110101101; // sop min sp
        MtmcExecInstruction(&emu, inst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(10 == MtmcFetchWordFromMemory(&emu, MtmcGetRegisterValue(&emu, SP)));
    }

    static void testSopMax(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 100, (short) 20);
        MtmcWriteWordToMemory(&emu, 98, (short) 10);

        short inst = 0b0010011110111101; // sop max sp
        MtmcExecInstruction(&emu, inst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(20 == MtmcFetchWordFromMemory(&emu, MtmcGetRegisterValue(&emu, SP)));
    }

    static void testSopMax2(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 98, (short) 10);
        MtmcWriteWordToMemory(&emu, 100, (short) 20);

        short inst = 0b0010011110111101; // sop max sp
        MtmcExecInstruction(&emu, inst);

        assert(100 == MtmcGetRegisterValue(&emu, SP));
        assert(20 == MtmcFetchWordFromMemory(&emu, MtmcGetRegisterValue(&emu, SP)));
    }

    static void testSopNot(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 98, (short) 0b01010101);

        short sopBnotInst = 0b0010011111001101; // sop not sp
        MtmcExecInstruction(&emu, sopBnotInst);

        assert(98 == MtmcGetRegisterValue(&emu, SP));
        assert(~0b01010101 == MtmcFetchWordFromMemory(&emu, 98));
    }

    static void testSopLnotWhenNonZero(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 98, (short) 1);

        short sopNotInst = 0b0010011111011101; // sop lnot sp
        MtmcExecInstruction(&emu, sopNotInst);

        assert(98 == MtmcGetRegisterValue(&emu, SP));
        assert(0 == MtmcFetchWordFromMemory(&emu, 98));
    }

    static void testSopLnotWhenZero(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 98, (short) 0);

        short sopNotInst = 0b0010011111011101; // sop not sp
        MtmcExecInstruction(&emu, sopNotInst);

        assert(98 == MtmcGetRegisterValue(&emu, SP));
        assert(1 == MtmcFetchWordFromMemory(&emu, 98));
    }

    static void testSopNeg(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, SP, 98);
        MtmcWriteWordToMemory(&emu, 98, (short) 10);

        short sopNegInst = 0b0010011111101101; // sop neg sp
        MtmcExecInstruction(&emu, sopNegInst);

        assert(98 == MtmcGetRegisterValue(&emu, SP));
        assert(-10 == MtmcFetchWordFromMemory(&emu, 98));
    }

    static void testPushImmediate(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, DR, 1024);

        short inst = (short) 0b0010111100001101; // pushi sp 1024
        MtmcExecInstruction(&emu, inst);

        assert(1024 == MtmcFetchWordFromMemory(&emu, MtmcGetRegisterValue(&emu, SP)));
    }

    static void testEqWhenEq(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1024);
        MtmcSetRegisterValue(&emu, T1, 1024);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011000000000001; // eq t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testEqWhenNotEq(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1024);
        MtmcSetRegisterValue(&emu, T1, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011000000000001; // eq t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testNeqWhenNeq(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1024);
        MtmcSetRegisterValue(&emu, T1, 1024);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011000100000001; // neq t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testNeqWhenNotNeq(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1024);
        MtmcSetRegisterValue(&emu, T1, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011000100000001; // neq t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testGtWhenGt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        MtmcSetRegisterValue(&emu, T1, 1);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011001000000001; // gt t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testGtWhenNotGt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1);
        MtmcSetRegisterValue(&emu, T1, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011001000000001; // gt t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testGteWhenGt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        MtmcSetRegisterValue(&emu, T1, 1);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011001100000001; // gte t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testGteWhenE(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        MtmcSetRegisterValue(&emu, T1, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011001100000001; // gte t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testGteWhenNotGte(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1);
        MtmcSetRegisterValue(&emu, T1, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011001100000001; // gte t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testLtWhenLt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1);
        MtmcSetRegisterValue(&emu, T1, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011010000000001; // lt t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testLtWhenNotLt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        MtmcSetRegisterValue(&emu, T1, 1);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011010000000001; // lt t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testLteWhenLt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1);
        MtmcSetRegisterValue(&emu, T1, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011010100000001; // lte t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testLteWhenE(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        MtmcSetRegisterValue(&emu, T1, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011010100000001; // lte t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testLteWhenNotLte(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        MtmcSetRegisterValue(&emu, T1, 1);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011010100000001; // lte t0 t1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testEqiWhenEq(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011100000000001; // eqi t0 1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testEqiWhenNotEq(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1024);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011100000000001; // eqi t0 1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testNeqiWhenNeq(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011100100000001; // neqi t0 1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testNeqiWhenNotNeq(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011100100000001; // neqi t0 1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testGtiWhenGt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011101000000001; // gti t0 1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testGtiWhenNotGt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011101000000001; // gti t0 1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testGteiWhenGt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011101100000001; // gte t0 1
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testGteiWhenE(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011101100000010; // gtei t0 2
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testGteiWhenNotGte(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011101100000010; // gtei t0 2
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testLtiWhenLt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011110000000010; // lti t0 2
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testLtiWhenNotLt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011110000000010; // lti t0 2
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testLteiWhenLt(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 1);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011110100000010; // ltei t0 2
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testLteiWhenE(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 2);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011110100000010; // ltei t0 2
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) != 0);
    }

    static void testLteiWhenNotLte(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 3);
        assert(MtmcIsFlagTestBitSet(&emu) == 0);

        short inst = (short) 0b0011110100000010; // ltei t0 2
        MtmcExecInstruction(&emu, inst);

        assert(MtmcIsFlagTestBitSet(&emu) == 0);
    }

    static void testLoadWord(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, DR, 10);
        MtmcWriteWordToMemory(&emu, 10, 20);
        assert(0 == MtmcGetRegisterValue(&emu, T0));

        short inst = (short) 0b1000000000000000; // lw t0 10
        MtmcExecInstruction(&emu, inst);

        assert(20 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testLoadWordOffset(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, DR, 10);
        MtmcSetRegisterValue(&emu, T1, 5);
        MtmcWriteWordToMemory(&emu, 15, 20);
        assert(0 == MtmcGetRegisterValue(&emu, T0));

        short inst = (short) 0b1000000100000001; // lwo t0 t1 10
        MtmcExecInstruction(&emu, inst);

        assert(20 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testLoadByte(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, DR, 10);
        MtmcWriteByteToMemory(&emu, 10,  20);
        assert(0 == MtmcGetRegisterValue(&emu, T0));

        short inst = (short) 0b1000001000000000; // lw t0 10
        MtmcExecInstruction(&emu, inst);

        assert(20 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testLoadByteOffset(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, DR, 10);
        MtmcSetRegisterValue(&emu, T1, 5);
        MtmcWriteByteToMemory(&emu, 15,  20);
        assert(0 == MtmcGetRegisterValue(&emu, T0));

        short inst = (short) 0b1000001100000001; // lwo t0 t1 10
        MtmcExecInstruction(&emu, inst);

        assert(20 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testSaveWord(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, DR, 10);
        MtmcSetRegisterValue(&emu, T0, 20);
        assert(0 == MtmcFetchWordFromMemory(&emu, 10));

        short inst = (short) 0b1000010000000000; // sw t0 10
        MtmcExecInstruction(&emu, inst);

        assert(20 == MtmcFetchWordFromMemory(&emu, 10));
    }

    static void testSaveWordWithOffset(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, DR, 10);
        MtmcSetRegisterValue(&emu, T0, 20);
        MtmcSetRegisterValue(&emu, T1, 10);
        assert(0 == MtmcFetchWordFromMemory(&emu, 20));

        short inst = (short) 0b1000010100000001; // swo t0 t1 10
        MtmcExecInstruction(&emu, inst);

        assert(20 == MtmcFetchWordFromMemory(&emu, 20));
    }

    static void testSaveByte(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, DR, 10);
        MtmcSetRegisterValue(&emu, T0, 20);
        assert(0 == MtmcFetchByteFromMemory(&emu, 10));

        short inst = (short) 0b1000011000000000; // sw t0 10
        MtmcExecInstruction(&emu, inst);

        assert(20 == MtmcFetchByteFromMemory(&emu, 10));
    }

    static void testSaveByteWithOffset(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, DR, 10);
        MtmcSetRegisterValue(&emu, T0, 20);
        MtmcSetRegisterValue(&emu, T1, 10);
        assert(0 == MtmcFetchByteFromMemory(&emu, 20));

        short inst = (short) 0b1000011100000001; // swo t0 t1 10
        MtmcExecInstruction(&emu, inst);

        assert(20 == MtmcFetchByteFromMemory(&emu, 20));
    }

    static void testLoadImmediate(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, DR, 20);
        assert(0 == MtmcGetRegisterValue(&emu, T0));

        short inst = (short) 0b1000111100000001; // li t0 t1 10
        MtmcExecInstruction(&emu, inst);

        assert(20 == MtmcGetRegisterValue(&emu, T0));
    }

    static void testLoadRegisterWord(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T1, 100);
        MtmcSetRegisterValue(&emu, T2, 0);
        MtmcWriteWordToMemory(&emu, 100, (short) 10); // value written to memory

        short loadWordInst = (short) 0b0100000000010010; // lw t0, t1, t2
        MtmcExecInstruction(&emu, loadWordInst);

        assert(10 == MtmcGetRegisterValue(&emu, T0)); // should be loaded into t0
    }

    static void testLoadWordRegisterWithOffset(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T1, 100);
        MtmcSetRegisterValue(&emu, T2, 5);
        MtmcWriteWordToMemory(&emu, 105, (short) 10); // value written to memory

        short loadWordInst = (short) 0b0100000000010010; // lw t0, t1, t2
        MtmcExecInstruction(&emu, loadWordInst);

        assert(10 == MtmcGetRegisterValue(&emu, T0)); // should be loaded into t0
    }

    static void testLoadByteRegister(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T1, 100);
        MtmcSetRegisterValue(&emu, T2, 0);
        MtmcWriteByteToMemory(&emu, 100,  10); // value written to memory

        short loadByteInst = (short) 0b0101000000010010; // lb t0, t1, t2
        MtmcExecInstruction(&emu, loadByteInst);

        assert(10 == MtmcGetRegisterValue(&emu, T0)); // should be loaded into t0
    }

    static void testLoadByteRegisterWithOffset(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T1, 100);
        MtmcSetRegisterValue(&emu, T2, 5);
        MtmcWriteByteToMemory(&emu, 105,  10); // value written to memory

        short loadByteInst = (short) 0b0101000000010010; // lb t0, t1, t2
        MtmcExecInstruction(&emu, loadByteInst);

        assert(10 == MtmcGetRegisterValue(&emu, T0)); // should be loaded into t0
    }

    static void testSaveRegisterWord(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, T1, 100);
        MtmcSetRegisterValue(&emu, T2, 0);

        short saveWordInst = (short) 0b0110000000010010; // sw t0, t1, t2
        MtmcExecInstruction(&emu, saveWordInst);

        assert(10 == MtmcFetchWordFromMemory(&emu, 100));
    }

    static void testSaveWordRegisterWithOffset(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, T1, 100);
        MtmcSetRegisterValue(&emu, T2, 5);

        short saveWordInst = (short) 0b0110000000010010; // sw t0, t1, t2
        MtmcExecInstruction(&emu, saveWordInst);

        assert(10 == MtmcFetchWordFromMemory(&emu, 105));
    }

    static void testSaveByteRegister(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, T1, 100);
        MtmcSetRegisterValue(&emu, T2, 0);

        short saveByteInst = (short) 0b0111000000010010; // sw t0, t1, t2
        MtmcExecInstruction(&emu, saveByteInst);

        assert(10 == MtmcFetchByteFromMemory(&emu, 100));
    }

    static void testSaveByteRegisterWithOffset(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 10);
        MtmcSetRegisterValue(&emu, T1, 100);
        MtmcSetRegisterValue(&emu, T2, 5);

        short saveByteInst = (short) 0b0111000000010010; // sw t0, t1, t2
        MtmcExecInstruction(&emu, saveByteInst);

        assert(10 == MtmcFetchByteFromMemory(&emu, 105));
    }

    static void testJumpRegister(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, T0, 50);
        short jumpIfZeroInst = (short) 0b1001000000000000; // jr t0
        MtmcExecInstruction(&emu, jumpIfZeroInst);
        assert(50 == MtmcGetRegisterValue(&emu, PC));
    }

    static void testJump(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, PC, 50);

        short jumpInst = (short) 0b1100000000010000; // j 16
        MtmcExecInstruction(&emu, jumpInst);

        assert(16 == MtmcGetRegisterValue(&emu, PC));
    }

    static void testJumpZeroIfFlagBitSetToZero(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetFlagTestBit(&emu, 0);
        short jumpIfZeroInst = (short) 0b1101000000010000; // jz 16
        MtmcExecInstruction(&emu, jumpIfZeroInst);
        assert(16 == MtmcGetRegisterValue(&emu, PC));
    }

    static void testJumpZeroIfFlagBitSetToOne(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetFlagTestBit(&emu, 1);
        short jumpIfZeroInst = (short) 0b1101000000010000; // jz 16
        MtmcExecInstruction(&emu, jumpIfZeroInst);
        assert(0 == MtmcGetRegisterValue(&emu, PC));
    }

    static void testJumpNotZeroIfFlagBitSetToZero(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetFlagTestBit(&emu, 0);
        short jumpIfZeroInst = (short) 0b1110000000010000; // jnz 16
        MtmcExecInstruction(&emu, jumpIfZeroInst);
        assert(0 == MtmcGetRegisterValue(&emu, PC));
    }

    static void testJumpNotZeroIfFlagBitSetToOne(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetFlagTestBit(&emu, 1);
        short jumpIfZeroInst = (short) 0b1110000000010000; // jnz 16
        MtmcExecInstruction(&emu, jumpIfZeroInst);
        assert(16 == MtmcGetRegisterValue(&emu, PC));
    }

    static void testJumpAndLink(void) {
        struct MtmcEmu emu = {0};
        _MtmcTestInit(&emu);
        MtmcSetRegisterValue(&emu, PC, 50);

        short callInst = (short) 0b1111000000010000; // jal 16
        MtmcExecInstruction(&emu, callInst);

        assert(16 == MtmcGetRegisterValue(&emu, PC));
        assert(50 == MtmcGetRegisterValue(&emu, RA));
    }


// }


int main(int argc, const char* argv[]) {
    testSysCall();
    testMov();
    testInc();
    testInc3();
    testDec();
    testDec3();
    testSeti();
    // testNoOp();
    testAdd();
    testSub();
    testMul();
    testDiv();
    testMod();
    testAnd();
    testOr();
    testXor();
    testShiftLeft();
    testShiftRight();
    testMin();
    testMin2();
    testMax();
    testMax2();
    testBitwiseNot();
    testNotWithZero();
    testNotWithNonZeros();
    testNegate();
    testImmediateInstruction();
    testPush();
    testPop();
    testDuplicate();
    testSwap();
    testDrop();
    testOver();
    testRot();
    testSopAdd();
    testSopSub();
    testSopMul();
    testSopDiv();
    testSopMod();
    testSopAnd();
    testSopOr();
    testSopXor();
    testSopShl();
    testSopShr();
    testSopMin();
    testSopMin2();
    testSopMax();
    testSopMax2();
    testSopNot();
    testSopLnotWhenNonZero();
    testSopLnotWhenZero();
    testSopNeg();
    testPushImmediate();
    testEqWhenEq();
    testEqWhenNotEq();
    testNeqWhenNeq();
    testNeqWhenNotNeq();
    testGtWhenGt();
    testGtWhenNotGt();
    testGteWhenGt();
    testGteWhenE();
    testGteWhenNotGte();
    testLtWhenLt();
    testLtWhenNotLt();
    testLteWhenLt();
    testLteWhenE();
    testLteWhenNotLte();
    testEqiWhenEq();
    testEqiWhenNotEq();
    testNeqiWhenNeq();
    testNeqiWhenNotNeq();
    testGtiWhenGt();
    testGtiWhenNotGt();
    testGteiWhenGt();
    testGteiWhenE();
    testGteiWhenNotGte();
    testLtiWhenLt();
    testLtiWhenNotLt();
    testLteiWhenLt();
    testLteiWhenE();
    testLteiWhenNotLte();
    testLoadWord();
    testLoadWordOffset();
    testLoadByte();
    testLoadByteOffset();
    testSaveWord();
    testSaveWordWithOffset();
    testSaveByte();
    testSaveByteWithOffset();
    testLoadImmediate();
    testLoadRegisterWord();
    testLoadWordRegisterWithOffset();
    testLoadByteRegister();
    testLoadByteRegisterWithOffset();
    testSaveRegisterWord();
    testSaveWordRegisterWithOffset();
    testSaveByteRegister();
    testSaveByteRegisterWithOffset();
    testJumpRegister();
    testJump();
    testJumpZeroIfFlagBitSetToZero();
    testJumpZeroIfFlagBitSetToOne();
    testJumpNotZeroIfFlagBitSetToZero();
    testJumpNotZeroIfFlagBitSetToOne();
    testJumpAndLink();
    return 0;
}
